workflows:
    commerce_opportunity_flow:
        entity_restrictions:
            opportunity_status_creation:
                attribute: opportunity
                field: status
                mode: disallow
                values:
                    - 'opportunity_status.won'
                    - 'opportunity_status.lost'
            opportunity_close_reason_creation:
                attribute: opportunity
                field: closeReason
            opportunity_close_revenue_creation:
                attribute: opportunity
                field: closeRevenue
            opportunity_status_open:
                attribute: opportunity
                field: status
                step: open
                mode: disallow
                values:
                    - 'opportunity_status.won'
                    - 'opportunity_status.lost'
            opportunity_close_reason_open:
                attribute: opportunity
                field: closeReason
                step: open
            opportunity_close_revenue_open:
                attribute: opportunity
                field: closeRevenue
                step: open
            opportunity_customer_won:
                attribute: opportunity
                step: won
                field: customerAssociation
            opportunity_status_won:
                attribute: opportunity
                step: won
                field: status
            opportunity_probability_won:
                attribute: opportunity
                step: won
                field: probability
            opportunity_budget_amount_won:
                attribute: opportunity
                step: won
                field: budgetAmount
            opportunity_close_revenue_won:
                attribute: opportunity
                step: won
                field: closeRevenue
            opportunity_close_date_won:
                attribute: opportunity
                step: won
                field: closeDate
            opportunity_close_reason_won:
                attribute: opportunity
                step: won
                field: closeReason
            opportunity_customer_lost:
                attribute: opportunity
                step: lost
                field: customerAssociation
            opportunity_status_lost:
                attribute: opportunity
                step: lost
                field: status
            opportunity_probability_lost:
                attribute: opportunity
                step: lost
                field: probability
            opportunity_budget_amount_lost:
                attribute: opportunity
                step: lost
                field: budgetAmount
            opportunity_close_revenue_lost:
                attribute: opportunity
                step: lost
                field: closeRevenue
            opportunity_close_date_lost:
                attribute: opportunity
                step: lost
                field: closeDate
            opportunity_close_reason_lost:
                attribute: opportunity
                step: lost
                field: closeReason
