workflows:
    commerce_opportunity_flow:
        transitions:
            __start__:
                step_to: open
                is_start: true
                is_hidden: true
                is_unavailable_hidden: true
                transition_definition: create_definition
                frontend_options:
                    pageComponent:
                        layout: separate
                        module: 'oroui/js/app/components/view-component'
                        options:
                            view: 'orosales/js/app/views/opportunity-status-select-view'
                form_options:
                    attribute_fields:
                        status:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\OpportunityStatusSelectType
                            options:
                                enum_code: opportunity_status
                                required: true
                                placeholder: false
                                constraints:
                                    - NotBlank: ~
                                choice_label: name
                                excluded_values:
                                    - won
                                    - lost
                        probability: ~
            develop:
                step_to: open
                is_unavailable_hidden: true
                frontend_options:
                    icon: fa-play
                    class: btn-primary
                    pageComponent:
                        layout: separate
                        module: 'oroui/js/app/components/view-component'
                        options:
                            view: 'orosales/js/app/views/opportunity-status-select-view'
                transition_definition: develop_definition
                form_options:
                    attribute_fields:
                        contact:
                            form_type: Oro\Bundle\ContactBundle\Form\Type\ContactSelectType
                            options:
                                new_item_property_name: firstName
                                configs:
                                    allowCreateNew: true
                                    renderedPropertyName: fullName
                                    placeholder: oro.contact.form.choose_contact
                                    result_template_twig: '@OroForm/Autocomplete/fullName/result.html.twig'
                                    selection_template_twig: '@OroForm/Autocomplete/fullName/selection.html.twig'
                        budget_amount:
                            form_type: Oro\Bundle\CurrencyBundle\Form\Type\MultiCurrencyType
                        status:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\OpportunityStatusSelectType
                            options:
                                enum_code: opportunity_status
                                required: true
                                placeholder: false
                                constraints:
                                    - NotBlank: ~
                                choice_label: name
                                excluded_values:
                                    - won
                                    - lost
                        probability: ~
                        close_date: ~
                        customer_need:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
                        proposed_solution:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
            close_won:
                step_to: won
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-check-circle-o'
                    class: 'btn-success'
                transition_definition: close_won_definition
                form_options:
                    attribute_fields:
                        close_revenue:
                            form_type: Oro\Bundle\CurrencyBundle\Form\Type\MultiCurrencyType
                        close_date:
                            options:
                                constraints:
                                    - NotBlank: ~
                    form_init:
                        - '@request_enum_entity': # set status if blank (to satisfy the validator)
                            conditions:
                                '@empty': [$status]
                            enum_code: opportunity_status
                            identifier: 'in_progress'
                            attribute: $opportunity.status
                        - '@create_date':
                            parameters:
                                attribute: $close_date
                        - '@clone_object':
                            target: $budget_amount
                            attribute: $close_revenue
            close_lost:
                step_to: lost
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-times'
                    class: 'btn-danger'
                transition_definition: close_lost_definition
                form_options:
                    attribute_fields:
                        close_reason_name:
                            form_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                            options:
                                required: true
                                placeholder: false
                                choices:
                                    Outsold: outsold
                                    Cancelled: cancelled
                                constraints:
                                    - NotBlank: ~
                        close_date:
                            options:
                                constraints:
                                    - NotBlank: ~
                    form_init:
                        - '@request_enum_entity': # set status if blank (to satisfy the validator)
                            conditions:
                                '@empty': [$status]
                            enum_code: opportunity_status
                            identifier: 'in_progress'
                            attribute: $opportunity.status
                        - '@create_date':
                            parameters:
                                attribute: $close_date
            reopen:
                step_to: open
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-backward'
                    class: 'btn-primary'
                    pageComponent:
                        layout: separate
                        module: 'oroui/js/app/components/view-component'
                        options:
                            view: 'orosales/js/app/views/opportunity-status-select-view'
                transition_definition: reopen_definition
                form_options:
                    attribute_fields:
                        contact:
                            form_type: Oro\Bundle\ContactBundle\Form\Type\ContactSelectType
                            options:
                                new_item_property_name: firstName
                                configs:
                                    allowCreateNew: true
                                    renderedPropertyName: fullName
                                    placeholder: oro.contact.form.choose_contact
                                    result_template_twig: '@OroForm/Autocomplete/fullName/result.html.twig'
                                    selection_template_twig: '@OroForm/Autocomplete/fullName/selection.html.twig'
                        budget_amount:
                            form_type: Oro\Bundle\CurrencyBundle\Form\Type\MultiCurrencyType
                        status:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\OpportunityStatusSelectType
                            options:
                                enum_code: opportunity_status
                                required: true
                                placeholder: false
                                constraints:
                                    - NotBlank: ~
                                choice_label: name
                                excluded_values:
                                    - won
                                    - lost
                        probability: ~
                        close_date: ~
                        customer_need:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
                        proposed_solution:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
                        notes:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
                    form_init:
                        - '@request_enum_entity':
                            enum_code: opportunity_status
                            order_by:
                                priority: ASC
                            attribute: $opportunity.status
                        - '@call_service_method':
                            service: oro_sales.provider.probability
                            method: get
                            method_parameters: [$opportunity.status]
                            attribute: $opportunity.probability
            quote_create:
               step_to: quote_created
               is_unavailable_hidden: true
               frontend_options:
                   icon: fa-list-alt
               transition_definition: quote_creating_definition
            quote_develop:
                step_to: quote_created
                is_unavailable_hidden: true
                frontend_options:
                    icon: fa-play
                    class: btn-primary
                    pageComponent:
                        layout: separate
                        module: 'oroui/js/app/components/view-component'
                        options:
                            view: 'orosales/js/app/views/opportunity-status-select-view'
                transition_definition: develop_definition
                form_options:
                    attribute_fields:
                        contact:
                            form_type: Oro\Bundle\ContactBundle\Form\Type\ContactSelectType
                            options:
                                new_item_property_name: firstName
                                configs:
                                    allowCreateNew: true
                                    renderedPropertyName: fullName
                                    placeholder: oro.contact.form.choose_contact
                                    result_template_twig: '@OroForm/Autocomplete/fullName/result.html.twig'
                                    selection_template_twig: '@OroForm/Autocomplete/fullName/selection.html.twig'
                        budget_amount:
                            form_type: Oro\Bundle\CurrencyBundle\Form\Type\MultiCurrencyType
                        status:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\OpportunityStatusSelectType
                            options:
                                enum_code: opportunity_status
                                required: true
                                placeholder: false
                                constraints:
                                    - NotBlank: ~
                                choice_label: name
                                excluded_values:
                                    - won
                                    - lost
                        probability: ~
                        close_date: ~
                        customer_need:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
                        proposed_solution:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
