features:
    enable_contact_request:
        label: oro.contactus.contactrequest.feature.label
        description: oro.contactus.contactrequest.feature.description
        toggle: oro_contact_us_bridge.enable_contact_request
        routes:
            - oro_contactus_bridge_contact_us_page
            - oro_contactus_bridge_request_create
