navigation:
    menu_config:
        items:
            # Start Requirement for "Default Theme 50/51"
            live_chat:
                label: 'oro.contact_us_bridge.frontend.navigation.items.live_chat.label'
                uri: '/contact-us'
                extras:
                    position: 15
            # End Requirement for "Default Theme 50/51"
            contact_us_at_last:
                label: 'oro.contact_us_bridge.frontend.navigation.items.contact_us.label'
                route: 'oro_contactus_bridge_contact_us_page'
                extras:
                    position: 15
            contact_us:
                label: 'oro.contact_us_bridge.frontend.navigation.items.contact_us.label'
                route: 'oro_contactus_bridge_contact_us_page'
        tree:
            # Start Requirement for "Default Theme 50/51"
            commerce_top_nav:
                children:
                    live_chat: ~
            # End Requirement for "Default Theme 50/51"

            commerce_top_nav_refreshing_teal:
                children:
                    contact_us_at_last: ~

            commerce_main_menu:
                children:
                    contact_us: ~

            commerce_footer_links:
                children:
                    information:
                        children:
                            contact_us: ~
    titles:
        oro_contactus_bridge_contact_us_page: 'oro.contactus.title'
